### ISSUE TITLE
[BUG] Doesn't start up

### ISSUE THREAD

**Issue by sc0p91** [Ooggle/FlipperAnimationManager#12]
**Describe the bug**
Trying to start the application - either selfcompiled or precompiled (.deb) doesn't work.
Starting via Termina:
```
» flipperam 
Error: open manifest.txt: No such file or directory
```
Starting via .destop entry -> Icon quickly shows up in Taskbar and then disapears.

**To Reproduce**
1. Install any way on Debian 12 + KDE

**Desktop (please complete the following information):**
- OS: Debian GNU/Linux 12 (bookworm) x86_64
- Host: 20UNCTO1WW ThinkPad X1 Nano Gen 1
- Kernel: 6.1.0-9-amd64
- DE: Plasma 5.27.5
- WM: KWin
- CPU: 11th Gen Intel i5-1140G7 (8) @ 4.200GHz
- GPU: Intel Tiger Lake-UP4 GT2 [Iris Xe Graphics]

**Additional context**
I'm not sure how this is supposed to work - I can't read that code & the Wiki [Usage Guide](https://github.com/Ooggle/FlipperAnimationManager/wiki/Usage-Guide) is empty. I tried running the binary inside an animation-Folder, with an manifest.txt in it, tried it with my flipper connected, with qFlipper open & closed - im clueless.

**Comment by Ooggle** [comment]
Hello, thanks for reporting. Could you confirm you encounter this problem on latest version (v1.3.1).

**Comment by sc0p91** [comment]
Yes, exactly: 1.3.1

**Comment by Ooggle** [comment]
Tested on a fresh installation of Debian 12 with KDE and Gnome, I did not encounter any issues with both X11 and Wayland backends. The error regarding manifest.txt comes from how the app is managed internally and it shows up everytime the application start, it's a normal behaviour.

Without any more context or stacktrace I will not be able to help since it may come from your packages or your OS configuration..

Environment tested on for reference:   
![image](https://github.com/Ooggle/FlipperAnimationManager/assets/33269056/0ae40a17-2b96-4900-a843-856b18fa2c86)

**Comment by sc0p91** [comment]
Thanks for looking into this.
I might be the only person out there having this issue - but if you want me to collect some more infos, I'll glady do that. 
I'm not sure how to collect stacktraces - are there any flags I can start the application with, to get some logs?

Some more sys-infos:

```
» echo -e "sdl2 ver.: $(sdl2-config --version)\n"; g++ --version; make --version 
sdl2 ver.: 2.28.2

g++ (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

![image](https://github.com/Ooggle/FlipperAnimationManager/assets/3425373/586b238f-0c73-4c4f-a8ab-7291df20a85b)

**Comment by Ooggle** [comment]
Maybe your version of SDL2 is not yet supported. There is no debug flag but if you can send me the output of the following commands, I can take a look at it and see if it's possible/easy to fix:   
```sh
sudo ltrace flipperam
sudo strace flipperam
```

**Comment by sc0p91** [comment]
compiled sdl by myself from the (official source)]https://www.libsdl.org/] 

The Issue with s- and ltrace - it hangs forever: Same if I try to start it from the console:
![image](https://github.com/Ooggle/FlipperAnimationManager/assets/3425373/abe33cd5-361e-4bf8-bf37-3543b460d4c8)

I let both run for a couple of seconds and attached it.
[tracelogs.zip](https://github.com/Ooggle/FlipperAnimationManager/files/12455661/tracelogs.zip)

**Comment by sc0p91** [comment]
Update:
I downgraded to libsdl2-dev version: 2.26.5 and now its running smoothly.
Thanks for the hint!
