### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by GamerPi** [Ooggle/FlipperAnimationManager#2]
Everything works perfectly for opening these files. I have a folder with 60 or so and when selecting all, the application just closes without any error. If there is a log I can submit that here.

**Comment by Ooggle** [comment]
Hello,
What version are you using?

This bug has been fixed in commit https://github.com/Ooggle/FlipperAnimationManager/commit/cdfddbc3de2334aa4cd90186d277603d434227ba and will be pushed in a new version (1.1) this week. Feel free to tell me if your version is superior or inferior to this commit.

**Comment by GamerPi** [comment]
Perfect, it was v1.0. Great work btw!

**Comment by Ooggle** [comment]
Thank you!
