### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by GamerPi** [Ooggle/FlipperAnimationManager#3]
Sorry to bring up another issue but as I attempted to build this project after cloning the repo, I was given a few errors when selecting release. Cannot open include file: 'SDL_opengl.h': No such file or directory. This error came up in line 70, 24, and line 8 (3 times.)

I will look into this on my end since it most likely is an error with me not having the SDL in the right folder. I did download the SDL listed but I placed it in the folder with the .SLN file

**Comment by Ooggle** [comment]
No worries, feel free to post anything you think it should be answered here.

I didn't explain it yet but you need to download the SDL2 library from [the releases](https://github.com/libsdl-org/SDL/releases) (the sdl2-devel-2.xx.x-vc.zip file) and copy it somewhere in your computer.

Then, go to project settings in Visual Studio and replace any `%SDL2_DIR%` you find in the compiler and linker section by the path of your SDL2 directory. An alternative method is to directly open the `FlipperAM.vcxproj` file and replace by hand every `%SDL2_DIR%` by the path of your SDL2 directory.

Tell me if it worked for you, I will update the readme and close myself the issue if everything's alright.

**Comment by GamerPi** [comment]
Everything worked wonders. I did have to do a few things on top of what you listed. I downloaded the most up to date SDL zip and extracted it to a folder and properly linked it, but I think just modifying the FlipperAM.vcxproj worked better. Also I had issues with Dirent, so all I did was copy that into the lib/imgui/backends. I also put a copy of the SDL folder in there just as a backup if I missed something. Once I completed that and moved the SDL2.dll into the release folder it works like a charm. Glad it doesn't crash now! 👍

**Comment by Ooggle** [comment]
Glad it worked for you! And yes I forgot to add the Dirent folder into the includes directories in the Visual Studio project, thanks for the heads up! I will add the previous documentation to the readme file soon so I close the issue here. Thank you for your support!
