### ISSUE TITLE
[Feature Request] Sub-folder Animation Support

### ISSUE THREAD

**Issue by ESurge** [Ooggle/FlipperAnimationManager#4]
First off, awesome project. Tried it out, and it works great!

I know that animations can be loaded within sub-folders and I was wondering if you could bring that into the app.

For example, having the below text in the manifest will work as long as the folders are correct.

```
Name: Sasquach/Sasquach_D1g1talRa1n_128x64
Min butthurt: 1
Max butthurt: 14
Min level: 1
Max level: 30
Weight: 1
```

The FlipperZero looks for the `Sasquach` folder, and then looks for the `Sasquach_D1g1talRa1n_128x64` folder to load the animation.

Thanks!

**Comment by Ooggle** [comment]
Hi, I didn't knew it was possible to do that on the Flipper!

Thank you for the detailed explanation of the inner working of subfolders loading, I will definitely add it to the tool.

**Comment by Ooggle** [comment]
Added in https://github.com/Ooggle/FlipperAnimationManager/commit/0ed3b1fc843eb12e9c0a6381eee5de8965549ce5 and will be pulled in the next release. I'm closing the issue, thank you!
