### ISSUE TITLE
Resizing window or entering fullscreen triggers layout failure

### ISSUE THREAD

**Issue by sdaitzman** [Ooggle/FlipperAnimationManager#5]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1499476/217005286-29147b42-8a5a-40f2-bc15-7839f64d960e.png">

Screenshot attached of the resulting layout issue. Please let me know if I can provide any other info to help, or if this is expected behavior. Flipper Animation Manager macOS x86_64 v1.2.1 on macOS 13.2.

**Comment by Ooggle** [comment]
Hello.
It seems that MacOS crash or behave incorrectly when `SDL_GetWindowSurface` is called to get the dimension of the window. I replaced it by `SDL_GetWindowSize` and now it seems to work fine.
Thank you for pointing this out, the fix will be available in the next release.
