### ISSUE TITLE
How to use the compiler?

### ISSUE THREAD

**Issue by Kf637** [Ooggle/FlipperAnimationManager#6]
I can't find anyting for the compiler that was released at [v1.3.0](https://github.com/Ooggle/FlipperAnimationManager/releases/tag/v1.3.0)

**Comment by Ooggle** [comment]
Hello,
The compile option is available when you click the `more` button of a png animation:
![image](https://user-images.githubusercontent.com/33269056/218335624-d04d79a7-29a1-401f-9fda-d1482f2e3d83.png)

**Comment by Kf637** [comment]
I don't see it
![image](https://user-images.githubusercontent.com/43268197/218337692-5f39ffe3-2b81-48a7-b771-1c9b9d94cd8b.png)

**Comment by Ooggle** [comment]
This animation is already compiled (.bm files). You can see if the animation is png or bm here:

![image](https://user-images.githubusercontent.com/33269056/218338059-783f488d-fa1e-445b-9fde-a631f623e9b3.png)

The option only appears on png animations to convert them to bm animations (Flipper animation format).

**Comment by Kf637** [comment]
Wfter changing path to the umcompiled animatioin it does not find any.

**Comment by Kf637** [comment]
![image](https://user-images.githubusercontent.com/43268197/218338888-fbbc0842-dd5d-4f93-b130-c48f44f81f58.png)

**Comment by Kf637** [comment]
I see the issue, it requires a meta.txt file, that should be in the docs.

**Comment by Ooggle** [comment]
Well, yes it requires a meta.txt because it's impossible to know how the animation should behave without it.
I will try to write a more concise guide [here](https://github.com/Ooggle/FlipperAnimationManager/wiki/Usage-Guide) for beginners when I get more time.

Do you have any more question?
