### ISSUE TITLE
Running make on Win

### ISSUE THREAD

**Issue by arudaev** [Ooggle/FlipperAnimationManager#8]
c:\...\FlipperAnimationManager> make
process_begin: CreateProcess(NULL, uname -s, ...) failed.
Makefile:26: pipe: No error
g++ -std=c++17 -Ilib -Ilib/imgui -Ilib/imgui/backends -g -Wall -Wformat `pkg-config --cflags sdl2` -c -o src/main.o src//main.cpp
g++: error: unrecognized command-line option '--cflags'
make: *** [Makefile:71: src/main.o] Error 1

I realized that that command was for linux, but the method is for win 😅

---

I also don't get the 
```
Select the Release configuration and build the project, the output binary will be located in Release folder.
```
 step in `Via VS Code`

**Comment by Ooggle** [comment]
Hello,

As for the Makefile, it is meant to be used with Linux or Windows using the [MSYS2 Unix like terminal](https://www.msys2.org/), as written in the readme. You can't use classic Powershell to run the Makefile.

For your second question, you need to use Visual Studio, not Visual Studio Code. The release configuration can be found on the top bar here:   
![image](https://user-images.githubusercontent.com/33269056/233307244-d8030bc8-8654-4996-a39b-b65c8ab09d93.png)

And after clicking on `Build` -> `Build Solution`, the compiled binary will be in the `Release` folder inside the git repository.

I hope I answered your questions, feel free to tell me if everything's working fine on your side.
